[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Agave Deshred"
url = "http://127.0.0.1:10002"
kind = "deshred"
x_token = ""

[[endpoint]]
name = "Local Processed"
url = "http://127.0.0.1:10002"
kind = "yellowstone"
x_token = ""
